### ISSUE TITLE
Break out the board definitions into separate or vendor files

### ISSUE THREAD

**Issue by majenkotech** [chipKIT32/PIC32-avrdude-bootloader#17]
The number of boards in the BoardConfig.h file is getting quite large now, and it's hard to navigate.  I would suggest breaking this board down into a "wrapper" file with all the top and bottom portions in it, and then move all the actual board configuration blocks out into separate header files (either a single header for each board, or multiple boards by the same vendor or in the same family together in a header) so that it's possible to just jump in to the board configuration you want (and to copy that section and edit it for a new board).

**Comment by EmbeddedMan** [comment]
Sounds like a great idea Matt!

*Brian

**Comment by EmbeddedMan** [comment]
Not only is this a good idea, it sounds like Keith might be doing this at some time in the future, primarily to cut down on the size of BoardConfig.h and make the source code much cleaner. When it does so, we will try and copy his changes over on this repo to stay as in sync as possible with the basic .c and .h files.

**Comment by EmbeddedMan** [comment]
I would say that this task has now been completed. Awesome job to Matt for breaking apart the BoardConfig file.
