### ISSUE TITLE
Post-compilation command

### ISSUE THREAD

**Issue by majenkotech** [chipKIT32/PIC32-avrdude-bootloader#3]
The post-compilation command to copy the .hex file to the bootloader images folder is a Windows specific command.

This breaks the compilation on people using a real operating system.

Why not just change the "ImagePath" in the project?

**Comment by EmbeddedMan** [comment]
OK, I've pushed a change from "copy" to "cp", as well as fixing the slash direction in the paths, for the post-build step. This should allow the post build copy step to run on Linux and Mac as well as Windows. I can't test on anything but Windows, but it still appears to work fine (with the "cp").

If somebody could please test this on Linux or Mac os and report back it it works or not, I'll close the issue if we can know that it works OK.

**Comment by EmbeddedMan** [comment]
I created a Linux VM, installed MPLAB X and XC32 v1.40, and confirmed that the change to "cp" does in fact work fine under Linux, as far as I can tell.
