### ISSUE TITLE
Link Error: Could not allocate

### ISSUE THREAD

**Issue by Bamaan** [chipKIT32/PIC32-avrdude-bootloader#38]
The bootloader works briljantly on a Fubarino mini. I want to compile the bootloader for a custom pcb with different parameters to switch between program and application state.
I can't however, get the FUBARINO_MINI_USB code to compile.
My compiler is the XC32 Free edition. 
This is the output from MPLABX:

`CLEAN SUCCESSFUL (total time: 79ms)
make -f nbproject/Makefile-FUBARINO_MINI_USB.mk SUBPROJECTS= .build-conf
make[1]: Entering directory '/home/gregoor/MPLABXProjects/PIC32-avrdude-bootloader/bootloaders/chipKIT-Bootloaders.X'
make  -f nbproject/Makefile-FUBARINO_MINI_USB.mk dist/FUBARINO_MINI_USB/production/chipKIT-Bootloaders.X.production.hex
make[2]: Entering directory '/home/gregoor/MPLABXProjects/PIC32-avrdude-bootloader/bootloaders/chipKIT-Bootloaders.X'
../cdcacm.c:1:0: warning: Compiler option (Optimize for size) ignored because the free XC32 C compiler does not support this feature. [enabled by default]
 /**** cdcacm.c ****************************************************************
 ^
cc1: note: Disable the option or visit http://www.microchip.com/MPLABXCcompilers to purchase a new MPLAB XC compiler license.
../main.c:1:0: warning: Compiler option (Optimize for size) ignored because the free XC32 C compiler does not support this feature. [enabled by default]
 /**** main.c ******************************************************************
 ^
cc1: note: Disable the option or visit http://www.microchip.com/MPLABXCcompilers to purchase a new MPLAB XC compiler license.
../usb.c:1:0: warning: Compiler option (Optimize for size) ignored because the free XC32 C compiler does not support this feature. [enabled by default]
 /**** usb.c *******************************************************************
 ^
cc1: note: Disable the option or visit http://www.microchip.com/MPLABXCcompilers to purchase a new MPLAB XC compiler license.
"/opt/microchip/xc32/v1.42/bin/xc32-gcc" -c -mprocessor=32MX250F128D -I.. -MMD -MF build/FUBARINO_MINI_USB/production/_ext/1472/crt0.o.d -o build/FUBARINO_MINI_USB/production/_ext/1472/crt0.o ../crt0.S -DXPRJ_FUBARINO_MINI_USB=FUBARINO_MINI_USB -no-legacy-libc -ftoplevel-reorder -Wa,--defsym=__MPLAB_BUILD=1,-MD=build/FUBARINO_MINI_USB/production/_ext/1472/crt0.o.asm.d,--gdwarf-2,-I.. 
"/opt/microchip/xc32/v1.42/bin/xc32-gcc" -g -x c -c -mprocessor=32MX250F128D -mips16 -mno-float -Os -D_BOARD_FUBARINO_MINI_USB_ -I.. -MMD -MF build/FUBARINO_MINI_USB/production/_ext/1472/cdcacm.o.d -o build/FUBARINO_MINI_USB/production/_ext/1472/cdcacm.o ../cdcacm.c -DXPRJ_FUBARINO_MINI_USB=FUBARINO_MINI_USB -no-legacy-libc -ftoplevel-reorder 
"/opt/microchip/xc32/v1.42/bin/xc32-gcc" -g -x c -c -mprocessor=32MX250F128D -mips16 -mno-float -Os -D_BOARD_FUBARINO_MINI_USB_ -I.. -MMD -MF build/FUBARINO_MINI_USB/production/_ext/1472/main.o.d -o build/FUBARINO_MINI_USB/production/_ext/1472/main.o ../main.c -DXPRJ_FUBARINO_MINI_USB=FUBARINO_MINI_USB -no-legacy-libc -ftoplevel-reorder 
"/opt/microchip/xc32/v1.42/bin/xc32-gcc" -g -x c -c -mprocessor=32MX250F128D -mips16 -mno-float -Os -D_BOARD_FUBARINO_MINI_USB_ -I.. -MMD -MF build/FUBARINO_MINI_USB/production/_ext/1472/usb.o.d -o build/FUBARINO_MINI_USB/production/_ext/1472/usb.o ../usb.c -DXPRJ_FUBARINO_MINI_USB=FUBARINO_MINI_USB -no-legacy-libc -ftoplevel-reorder 
"/opt/microchip/xc32/v1.42/bin/xc32-gcc"   -mprocessor=32MX250F128D -nostdlib -nostartfiles -mips16 -mno-float -o dist/FUBARINO_MINI_USB/production/chipKIT-Bootloaders.X.production.elf build/FUBARINO_MINI_USB/production/_ext/1472/main.o build/FUBARINO_MINI_USB/production/_ext/1472/crt0.o build/FUBARINO_MINI_USB/production/_ext/1472/cdcacm.o build/FUBARINO_MINI_USB/production/_ext/1472/usb.o          -DXPRJ_FUBARINO_MINI_USB=FUBARINO_MINI_USB  -no-legacy-libc  -ftoplevel-reorder   -Wl,--defsym=__MPLAB_BUILD=1,--script="../MX1-2-USB-boot-linkerscript.ld",--no-code-in-dinit,--no-dinit-in-serial-mem,-L"../../../../../../opt/microchip/xc32/v1.42/pic32mx/lib",-L"../../../../../../../../Program Files (x86)/Microchip/MPLAB C32 Suite/lib",-L"../../../../../../../../Program Files (x86)/Microchip/MPLAB C32 Suite/pic32mx/lib",-Map="dist/FUBARINO_MINI_USB/production/MX7cK.X.production.map",--memorysummary,dist/FUBARINO_MINI_USB/production/memoryfile.xml,-Os
nbproject/Makefile-FUBARINO_MINI_USB.mk:188: recipe for target 'dist/FUBARINO_MINI_USB/production/chipKIT-Bootloaders.X.production.hex' failed
make[2]: Leaving directory '/home/gregoor/MPLABXProjects/PIC32-avrdude-bootloader/bootloaders/chipKIT-Bootloaders.X'
nbproject/Makefile-FUBARINO_MINI_USB.mk:97: recipe for target '.build-conf' failed
make[1]: Leaving directory '/home/gregoor/MPLABXProjects/PIC32-avrdude-bootloader/bootloaders/chipKIT-Bootloaders.X'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed
/opt/microchip/xc32/v1.42/bin/bin/gcc/pic32mx/4.8.3/../../../../bin/xc32-ld: dist/FUBARINO_MINI_USB/production/chipKIT-Bootloaders.X.production.elf section '.splitrodata' will not fit in region 'split_program_mem'
build/FUBARINO_MINI_USB/production/_ext/1472/main.o: Link Error: Could not allocate section .text, size = 3208 bytes, attributes = code 
 Link Error: Could not allocate program memory
collect2: error: ld returned 255 exit status
make[2]: *** [dist/FUBARINO_MINI_USB/production/chipKIT-Bootloaders.X.production.hex] Error 255
make[1]: *** [.build-conf] Error 2
make: *** [.build-impl] Error 2`

`BUILD FAILED (exit value 2, total time: 899ms)`

When I try to build FUBARINO_SDZ_UART the build is successful.

Thanks in advance!

**Comment by EmbeddedMan** [comment]
Yeah, unfortunately, the USB based bootloaders for 3K boot flash devices
(like the FB Mini) require the fully optimized XC32 - the free version
doesn't get the code small enough.

There are a couple ways for you to solve this problem:

1) Buy the full version (seems silly just for this one compile)
2) Use the chipKIT compiler that comes with chipKIT-core. This compiler
(Which is based on XC32) has full optimizations and will build the
bootloader.
3) If you send me your files, I can build your bootloader for you, as I
have a full version of XC32

To the other chipKIT-devs : it would be really nice, in our next version of
the bootloader, to move things around a bit more so that we could not only
leave a whole for the MPLAB X debug exec, but also allow building all
bootloaders with the free version of XC32. We could do this by moving more
of the bootloader out of the boot flash region.

*Brian

**Comment by Bamaan** [comment]
Thank you very much. I got it working with chipKIT-core. 
For anyone who is interested:
- Download chipKIT-core [zip file](http://chipkit.net/wiki/index.php?title=ChipKIT_core) for your platform
- Extract zip (I placed it in the microchip folder alongside the xc32 directory)
- Open MPLABX and go to Tools->Options->Embedded->Build Tools
- Click Add.. to add a new toolchain and select the bin deirectory within chipKIT core. (In my case /opt/microchip/chipkit-core/pic32/compiler/pic32-tools/bin)
- MPLABX will recognize it as C32 and click ok.
- Go to your project properties and select your new toolchain

If you have any questions, I will gladly awnser them as Brain did with mine.

Thanks again Brian!

Gregoor

**Comment by NikhilMG007** [comment]
Hi Bamaan and Brian, 
I face the same issue with SAME70 controller. 
When I compile bootloader project, Link error: Could not allocate section.
I tried to use the same compiler, but when I create new project with same70 device, I cannot select chipkit compiler. It appears only for pic controllers. 
Is there any alternative for SAM controllers?

regards,
Nikhil

**Comment by majenkotech** [comment]
> Hi Bamaan and Brian, I face the same issue with SAME70 controller. When I compile bootloader project, Link error: Could not allocate section. I tried to use the same compiler, but when I create new project with same70 device, I cannot select chipkit compiler. It appears only for pic controllers. Is there any alternative for SAM controllers?
> 
> regards, Nikhil

This bootloader (and the support for it) is for PIC32 microcontrollers only. The compiler, and our knowledge, is limited only to PIC32 microcontrollers, not ARM microcontrollers. You should therefore check out some of the Arduino boards to see if there are any SAME70 based boards that have a suitable bootloader (if a bootloader is even needed - I do know that some SAM boards have bootloaders in ROM).

**Comment by NikhilMG007** [comment]
> > Hi Bamaan and Brian, I face the same issue with SAME70 controller. When I compile bootloader project, Link error: Could not allocate section. I tried to use the same compiler, but when I create new project with same70 device, I cannot select chipkit compiler. It appears only for pic controllers. Is there any alternative for SAM controllers?
> > regards, Nikhil
> 
> This bootloader (and the support for it) is for PIC32 microcontrollers only. The compiler, and our knowledge, is limited only to PIC32 microcontrollers, not ARM microcontrollers. You should therefore check out some of the Arduino boards to see if there are any SAME70 based boards that have a suitable bootloader (if a bootloader is even needed - I do know that some SAM boards have bootloaders in ROM).


For SAM controllers bootloader resides in flash memory. When I add bootloader in Code configurator, for certain parts of the code, memory allocation fails and link error appears. Not sure if the issue is in compiler. Anyways thanks for the reply.
