### ISSUE TITLE
small config problem in MPLAB-X ( "set Configuration option" for Lenny Board is missing ) 

### ISSUE THREAD

**Issue by ESP32DE** [chipKIT32/PIC32-avrdude-bootloader#40]
hi
i downloaded the PIC32-avrdude-bootloader and loaded it in MPLAB X IDE v4.05
i want try to compile the bootloader for the Lenny Board ( Majenko ) and saw, 
that there is [majenko.h available and Lenny Board is on the list](https://github.com/chipKIT32/PIC32-avrdude-bootloader/blob/master/bootloaders/configs/majenko.h#L586)
but the "set Configuration" ( right click on Main Project folder ) to this was missing.

![grafik](https://user-images.githubusercontent.com/16070445/34366768-f4314458-eaa0-11e7-837f-012dcab32dd9.png)

so i did open the "customize" and created over "Manage Configurations"
a new "MAJENKO_LENNY" 

![grafik](https://user-images.githubusercontent.com/16070445/34366674-8cc50e36-ea9f-11e7-88fa-56a4914f8a1d.png)

with PIC32MX270F256D and PICKit3 and XC 1.44 compiler and set it to active.

![grafik](https://user-images.githubusercontent.com/16070445/34366680-a362b940-ea9f-11e7-9366-5e13fa0cfff7.png)

after set this config as active, i saw, that in "majenko.h" never "_BOARD_MAJENKO_LENNY_" config highlighted - there is highlighted "_BOARD_MAJENKO_ULTRANANO_" and i think this is wrong.

![grafik](https://user-images.githubusercontent.com/16070445/34366690-ea7bfb8e-ea9f-11e7-9b08-de387c1793ea.png)

a test with a compile, and upload with PICkit3  there is opposite the highlighted "ULTRANANO" PIC32MX270F256D as Device ( left bottom corner ) but i think this comes from the "RGB_STATION_USB_BLE" Board. 

for a simply test, i changed the PIC in Lenny Config from 256D to 128D for look,
does this make a change - but did not. the 270F256D comes from the "RGB_STATION_USB_BLE" board then.

![grafik](https://user-images.githubusercontent.com/16070445/34367080-5474ca24-eaa6-11e7-9fb9-9498f6b42549.png)

can someone check this or better - can someone add the "set configuration" for the "Board Lenny"?
or is this a "bug" in MPLAP-X?

i want test the Bootloader Program Button on RB13 or RA10 on a Breadboard Version with an PIC32MX270F256D with same setup like the Lenny Board is for deeper learn and how it works.

thank you so much!
best wishes
rudi ;-)

**Comment by EmbeddedMan** [comment]
The configuration for the Lenny was missing. I have added it in pull request #42, and the hex file is now in the repo for you as well. 

I tested the resulting hex file out on my Lenny, and it worked for me. Please feel free to reopen this issue if you can't get it to work for you.
