### ISSUE TITLE
Add support for Fubarino Mini v2.0

### ISSUE THREAD

**Issue by EmbeddedMan** [chipKIT32/PIC32-avrdude-bootloader#47]
This new configuration can be identical to the RGB Station, as they both use USB bootloader and the PIC32MX270 CPU.

**Comment by EmbeddedMan** [comment]
Resolved with new configuration and hex file. Tested on RGB station hardware and works.

**Comment by ricklon** [comment]
Great. Can't wait to test it.

--Rick
